const char opencl___blur[] = 


#if defined(OPENCL_DBG_MODE)


" /**                                                                                      \n"
"  * @brief   OpenCL kernel used to calculate equation resolver for                        \n"
"  *          reverse barrel distortion correction.                                        \n"
"  *                                                                                       \n"
"  * @file    from_barrel.c                                                                \n"
"  * @author  OSi (Ondrej Sienczak)                                                        \n"
"  */                                                                                      \n"
"                                                                                          \n"
"                                                                                          \n"
" /**                                                                                      \n"
"  * @brief   Indexes of arguments                                                         \n"
"  */                                                                                      \n"
" enum ArgIdx                                                                              \n"
" {                                                                                        \n"
"     ITEMS_CNT,      /**< @brief Count of items to be calculated */                       \n"
"     K0,             /**< @brief First polynomial constant */                             \n"
"     K1,             /**< @brief Second polynomial constant */                            \n"
"     K2,             /**< @brief Third polynomial constant */                             \n"
"     CENTER_X,       /**< @brief X coordinate of center of barrel distortion */           \n"
"     CENTER_Y,       /**< @brief Y coordinate of center of barrel distortion */           \n"
"     __ARGS_CNT      /**< @brief Count of arguments */                                    \n"
" };                                                                                       \n"
"                                                                                          \n"
"                                                                                          \n"
" /**                                                                                      \n"
"  * @brief   Argument type                                                                \n"
"  */                                                                                      \n"
" union Arg                                                                                \n"
" {                                                                                        \n"
"     float f;        /**< @brief Argument of float type */                                \n"
"     int   i;        /**< @brief Argument of integer type */                              \n"
" };                                                                                       \n"
"                                                                                          \n"
"                                                                                          \n"
" /**                                                                                      \n"
"  * @brief   Coordinates structure                                                        \n"
"  */                                                                                      \n"
" struct Vector                                                                            \n"
" {                                                                                        \n"
"     int x;  /**< @brief X coordinate */                                                  \n"
"     int y;  /**< @brief Y coordinate */                                                  \n"
" };                                                                                       \n"
"                                                                                          \n"
"                                                                                          \n"
" /**                                                                                      \n"
"  * @brief   Accumulated root of polynom                                                  \n"
"  *                                                                                       \n"
"  * @param   x   X coordinate of equation                                                 \n"
"  * @param   y   Y coordinate of equation                                                 \n"
"  * @param   k0  First polynomial constant                                                \n"
"  * @param   k1  Second polynomial constant                                               \n"
"  * @param   k2  Third polynomial constant                                                \n"
"  *                                                                                       \n"
"  * @return  Calculated root                                                              \n"
"  */                                                                                      \n"
" float _acc(float x,                                                                      \n"
"            float y,                                                                      \n"
"            float k0,                                                                     \n"
"            float k1,                                                                     \n"
"            float k2)                                                                     \n"
" {                                                                                        \n"
"     float         rq = x * x + y * y;                                                    \n"
"     return 1.0F + rq * (k0 + rq * (k1 + rq * k2));                                       \n"
" }                                                                                        \n"
"                                                                                          \n"
"                                                                                          \n"
" /**                                                                                      \n"
"  * @brief   Barrel distortion reverse equation disolver                                  \n"
"  *                                                                                       \n"
"  * @param   inX     Input X coordinates                                                  \n"
"  * @param   inY     Input Y coordinates                                                  \n"
"  * @param   outX    Output X coordinates                                                 \n"
"  * @param   outY    Output Y coordinates                                                 \n"
"  * @param   args    Arguments of filter                                                  \n"
"  */                                                                                      \n"
" void kernel fromBarrel(global struct Vector*       out,                                  \n"
"                        global const struct Vector* in,                                   \n"
"                        global const union Arg*     args)                                 \n"
" {                                                                                        \n"
"     const int   id    = get_global_id(0);    /* Current thread ID */                     \n"
"     const int   cnt   = get_global_size(0);  /* Count of threads */                      \n"
"                                                                                          \n"
"     const int   items = args[ITEMS_CNT].i;   /* Count of items needs to be calculated */ \n"
"     const float k0    = args[K0].f;          /* Constants used for calculation */        \n"
"     const float k1    = args[K1].f;                                                      \n"
"     const float k2    = args[K2].f;                                                      \n"
"     const int   cX    = args[CENTER_X].i;                                                \n"
"     const int   cY    = args[CENTER_Y].i;                                                \n"
"                                                                                          \n"
"     const int   ratio = items / cnt;         /* Number of elements for each thread */    \n"
"     const int   begin = ratio * id;                                                      \n"
"     const int   end   = ratio * (id + 1);                                                \n"
"                                                                                          \n"
"     /*                                                                                   \n"
"      * Here begins code to be processed in parallel.                                     \n"
"      *                                                                                   \n"
"      * We have barrel distortion described by its                                        \n"
"      * equation. This code process equation resolver                                     \n"
"      * running parallel on target processor (GPU).                                       \n"
"      */                                                                                  \n"
"     for (int i = begin; i < end; ++i)                                                    \n"
"     {                                                                                    \n"
"         /*                                                                               \n"
"          * Calculates first guess. This will not be so close to reality,                 \n"
"          * but we have to start somewhere.                                               \n"
"          */                                                                              \n"
"         const float dx     = in[i].x - cX;                                               \n"
"         const float dy     = in[i].y - cY;                                               \n"
"         float       acc    = _acc(dx, dy, k0, k1, k2);                                   \n"
"         float       guessX = dx * acc;                                                   \n"
"         float       guessY = dy * acc;                                                   \n"
"                                                                                          \n"
"         for (int j = 0; j < 64; ++j)                                                     \n"
"         {                                                                                \n"
"             /*                                                                           \n"
"              * Calculates equation final value from guess                                \n"
"              */                                                                          \n"
"             acc            = _acc(guessX, guessY, k0, k1, k2);                           \n"
"                                                                                          \n"
"             /*                                                                           \n"
"              * Guess is usually different from reality, so we have to                    \n"
"              * do correction of guess. We can use difference between                     \n"
"              * guess and reality to get correct direction to equation                    \n"
"              * solution.                                                                 \n"
"              */                                                                          \n"
"             float realityX = guessX / acc;                                               \n"
"             realityX       = guessX / acc;                                               \n"
"             guessX        += dx;                                                         \n"
"             guessX        -= realityX;                                                   \n"
"                                                                                          \n"
"             float realityY = guessY / acc;                                               \n"
"             guessY        += dy;                                                         \n"
"             guessY        -= realityY;                                                   \n"
"         }                                                                                \n"
"                                                                                          \n"
"         /*                                                                               \n"
"          * 64-times corrected guess should be pretty close to                            \n"
"          * to equation solution.                                                         \n"
"          */                                                                              \n"
"         out[i].x = (int)(guessX + cX);                                                   \n"
"         out[i].y = (int)(guessY + cY);                                                   \n"
"     }                                                                                    \n"
" }                                                                                        \n"


#else /* defined(OPENCL_DBG_MODE) */


"enum _E{_C,K0,K1,K2,_1,_2,_z};union _A{float f;int i;};struct _v{int x;int y"
";};float _0(float x,float y,float k0,float k1,float k2){float rq=x*x+y*y;ret"
"urn 1.0F+rq*(k0+rq*(k1+rq*k2));}void kernel fromBarrel(global struct _v*_3,g"
"lobal const struct _v*in,global const union _A*_a){const int id=get_global_i"
"d(0);const int _c=get_global_size(0);const int _i=_a[_C].i;const float k0=_a"
"[K0].f;const float k1=_a[K1].f;const float k2=_a[K2].f;const int cX=_a[_1].i"
";const int cY=_a[_2].i;const int _r=_i/_c;const int _b=_r*id;const int _e=_r"
"*(id+1);for(int i=_b;i<_e;++i){const float dx=in[i].x-cX;const float dy=in[i"
"].y-cY;float _9=_0(dx,dy,k0,k1,k2);float _5=dx*_9;float _6=dy*_9;for(int j=0"
";j<64;++j){_9=_0(_5,_6,k0,k1,k2);float _7=_5/_9;_7=_5/_9;_5+=dx;_5-=_7;float"
" _8=_6/_9;_6+=dy;_6-=_8;}_3[i].x=(int)(_5+cX);_3[i].y=(int)(_6+cY);}}"


#endif /* defined(OPENCL_DBG_MODE) */


;


const unsigned opencl___blur_len = sizeof(opencl___blur);
