const char opencl___correl8[] = 


#if defined(OPENCL_DBG_MODE)


" /**                                                                                                               \n"
"  * @brief   OpenCL kernel used for calculation of corelation.                                                     \n"
"  *                                                                                                                \n"
"  * @file    corelate.c                                                                                            \n"
"  * @author  OSi (Ondrej Sienczak)                                                                                 \n"
"  */                                                                                                               \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
" /**                                                                                                               \n"
"  * @brief   Indexes of arguments                                                                                  \n"
"  */                                                                                                               \n"
" enum Correl8_ArgIdx                                                                                               \n"
" {                                                                                                                 \n"
"     CORREL8___WIDTH_CURRENT,  /**< @brief Current frame width */                                                  \n"
"     CORREL8___WIDTH_PREVIOUS, /**< @brief Previous frame width */                                                 \n"
"     CORREL8___FIELD_X,        /**< @brief X coordinate of field */                                                \n"
"     CORREL8___FIELD_Y,        /**< @brief Y coordinate of field */                                                \n"
"     CORREL8___FIELD_SIZE,     /**< @brief Size of field */                                                        \n"
"     CORREL8___HEIGHT,         /**< @brief Frame height */                                                         \n"
"     CORREL8___OFFSET_X,       /**< @brief X Offset */                                                             \n"
"     CORREL8___OFFSET_Y,       /**< @brief Y Offset */                                                             \n"
"     CORREL8___MAX_SHIFT,      /**< @brief Maximal correlation shift */                                            \n"
"     __CORREL8___ARGS_CNT      /**< @brief Count of arguments */                                                   \n"
" };                                                                                                                \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
" /**                                                                                                               \n"
"  * @brief   Correlate frames to find best match                                                                   \n"
"  *                                                                                                                \n"
"  * @param result    Result of all correlation for every shift                                                     \n"
"  * @param current   Current image buffer                                                                          \n"
"  * @param previous  Previous (corelated) image buffer                                                             \n"
"  * @param args      Arguments                                                                                     \n"
"  */                                                                                                               \n"
" void kernel correl8(global int*                result,                                                            \n"
"                     global const unsigned int* current,                                                           \n"
"                     global const unsigned int* previous,                                                          \n"
"                     global const int*          args)                                                              \n"
" {                                                                                                                 \n"
"     int widthCurrent   = args[CORREL8___WIDTH_CURRENT];                                                           \n"
"     int widthPrevious  = args[CORREL8___WIDTH_PREVIOUS];                                                          \n"
"     int field_x        = args[CORREL8___FIELD_X];                                                                 \n"
"     int field_y        = args[CORREL8___FIELD_Y];                                                                 \n"
"     int field_size     = args[CORREL8___FIELD_SIZE];                                                              \n"
"     int height         = args[CORREL8___HEIGHT];                                                                  \n"
"     int offsetX        = args[CORREL8___OFFSET_X];                                                                \n"
"     int offsetY        = args[CORREL8___OFFSET_Y];                                                                \n"
"     unsigned maxShift  = args[CORREL8___MAX_SHIFT];                                                               \n"
"                                                                                                                   \n"
"     unsigned       idx = get_global_id(0);                                                                        \n"
"     offsetX     += idx % maxShift;                                                                                \n"
"     offsetY     += idx / maxShift;                                                                                \n"
"                                                                                                                   \n"
"     int s2 = field_size / 2;                                                                                      \n"
"     int x  = field_x    - s2;                                                                                     \n"
"     int y  = field_y    - s2;                                                                                     \n"
"                                                                                                                   \n"
"     unsigned int               sum  = 0;                                                                          \n"
"     global const unsigned int* curr = current  + (((x          ) + (y          ) * widthCurrent)  / sizeof(int)); \n"
"     global const unsigned int* prev = previous + (((x + offsetX) + (y + offsetY) * widthPrevious) / sizeof(int)); \n"
"                                                                                                                   \n"
"     for (int j = 0; j < field_size; ++j)                                                                          \n"
"     {                                                                                                             \n"
"         for (int k = 0; k < field_size; k++)                                                                      \n"
"         {                                                                                                         \n"
"             unsigned v = *curr;                                                                                   \n"
"             int      s = (v         & 0x000000FF);                                                                \n"
"             s         += ((v >> 8)  & 0x000000FF);                                                                \n"
"             s         += ((v >> 16) & 0x000000FF);                                                                \n"
"             s         += (v >> 24);                                                                               \n"
"                                                                                                                   \n"
"             v = *prev;                                                                                            \n"
"             s -= (v         & 0x000000FF);                                                                        \n"
"             s -= ((v >> 8)  & 0x000000FF);                                                                        \n"
"             s -= ((v >> 16) & 0x000000FF);                                                                        \n"
"             s -= (v >> 24);                                                                                       \n"
"                                                                                                                   \n"
"             sum += abs(s);                                                                                        \n"
"             ++curr;                                                                                               \n"
"             ++prev;                                                                                               \n"
"         }                                                                                                         \n"
"                                                                                                                   \n"
"         curr += (widthCurrent  - field_size);                                                                     \n"
"         prev += (widthPrevious - field_size);                                                                     \n"
"     }                                                                                                             \n"
"                                                                                                                   \n"
"     result[idx] = sum;                                                                                            \n"
" }                                                                                                                 \n"


#else /* defined(OPENCL_DBG_MODE) */


"enum _2_b{_2_1,_2_0,_2_7,_2_8,_2_2,_2_9,_2_5,_2_6,_2_3,_2_4};void kernel cor"
"rel8(global int*_2_17,global const unsigned int*_2_14,global const unsigned "
"int*_2_11,global const int*_2_19){int _2_d=_2_19[_2_1];int _2_c=_2_19[_2_0];"
"int _2_12=_2_19[_2_7];int _2_13=_2_19[_2_8];int _2_f=_2_19[_2_2];int _2_18=_"
"2_19[_2_9];int _2_15=_2_19[_2_5];int _2_16=_2_19[_2_6];unsigned _2_10=_2_19["
"_2_3];unsigned _2_1e=get_global_id(0);_2_15+=_2_1e%_2_10;_2_16+=_2_1e/_2_10;"
"int s2=_2_f/2;int x=_2_12-s2;int y=_2_13-s2;unsigned int _2_1c=0;global cons"
"t unsigned int*_2_1a=_2_14+(((x)+(y)*_2_d)/sizeof(int));global const unsigne"
"d int*_2_1b=_2_11+(((x+_2_15)+(y+_2_16)*_2_c)/sizeof(int));for(int j=0;j<_2_"
"f;++j){for(int k=0;k<_2_f;k++){unsigned v=*_2_1a;int s=(v & 0x000000FF);s+=("
"(v>>8)& 0x000000FF);s+=((v>>16)& 0x000000FF);s+=(v>>24);v=*_2_1b;s-=(v & 0x0"
"00000FF);s-=((v>>8)& 0x000000FF);s-=((v>>16)& 0x000000FF);s-=(v>>24);_2_1c+="
"abs(s);++_2_1a;++_2_1b;}_2_1a+=(_2_d-_2_f);_2_1b+=(_2_c-_2_f);}_2_17[_2_1e]="
"_2_1c;}"


#endif /* defined(OPENCL_DBG_MODE) */


;


const unsigned opencl___correl8_len = sizeof(opencl___correl8);
