const char opencl___blur_h[] = 


#if defined(OPENCL_DBG_MODE)


" /**                                                                                                               \n"
"  * @brief   OpenCL kernel used for horizontal bluring.                                                            \n"
"  *                                                                                                                \n"
"  * @file    blur_h.c                                                                                              \n"
"  * @author  OSi (Ondrej Sienczak)                                                                                 \n"
"  */                                                                                                               \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
" typedef unsigned char uint8_t;                                                                                    \n"
" typedef int           uint32_t;                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
" /**                                                                                                               \n"
"  * @brief   Kernel arguments                                                                                      \n"
"  */                                                                                                               \n"
" struct Args                                                                                                       \n"
" {                                                                                                                 \n"
"     const uint32_t width;      /**< @brief Frame width */                                                         \n"
"     const uint32_t height;     /**< @brief Frame height */                                                        \n"
"     const uint32_t dst_strive; /**< @brief Destination line size */                                               \n"
"     const uint32_t src_strive; /**< @brief Source line size */                                                    \n"
"     const uint32_t size;       /**< @brief Count of items to be calculated */                                     \n"
" };                                                                                                                \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
" /**                                                                                                               \n"
"  * @brief   Horizontal blur operation                                                                             \n"
"  *                                                                                                                \n"
"  * @param   dst     Destination buffer                                                                            \n"
"  * @param   src     Source buffer                                                                                 \n"
"  * @param   args    Arguments of filter                                                                           \n"
"  */                                                                                                               \n"
" void kernel blurH(global uint8_t*           dst,                                                                  \n"
"                   global const uint8_t*     src,                                                                  \n"
"                   global const struct Args* args)                                                                 \n"
" {                                                                                                                 \n"
"     const int             y     = get_global_id(0);           /* Current thread ID is current row */              \n"
"     global const uint8_t* start = src  + y * args->src_strive; /* Start and end of kernel */                      \n"
"     global const uint8_t* end   = start;                                                                          \n"
"     const int             size  = args->size;                                                                     \n"
"     const int             size2 = size / 2;                   /* Size of one side of the kernel without center */ \n"
"     unsigned int          acc   = (*start) * (size2 + 1);     /* Left half of kernel with first pixel */          \n"
"                                                                                                                   \n"
"     /* Right half of kernel */                                                                                    \n"
"     for (int k = 0; k < size2; ++k)                                                                               \n"
"     {                                                                                                             \n"
"         acc += (*end);                                                                                            \n"
"         end++;                                                                                                    \n"
"     }                                                                                                             \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"     global uint8_t* current = dst  + y * args->dst_strive;   /* Current destination pixel */                      \n"
"     const int       width   = args->width;                                                                        \n"
"                                                                                                                   \n"
"     /* Go through the image */                                                                                    \n"
"     for (int x = 0; x < width; ++x)                                                                               \n"
"     {                                                                                                             \n"
"         acc = acc + (*end) - (*start);                                                                            \n"
"                                                                                                                   \n"
"         if (x > size2)                                                                                            \n"
"         {                                                                                                         \n"
"             start++;                                                                                              \n"
"         }                                                                                                         \n"
"                                                                                                                   \n"
"         if (x < (width - size2 - 1))                                                                              \n"
"         {                                                                                                         \n"
"             end++;                                                                                                \n"
"         }                                                                                                         \n"
"                                                                                                                   \n"
"         *current = acc / size;                                                                                    \n"
"         ++current;                                                                                                \n"
"     }                                                                                                             \n"
"                                                                                                                   \n"
"     if (y < 128)                                                                                                  \n"
"     {                                                                                                             \n"
"         for (global char* i = dst, * const e = dst + 128; i != e; ++i)                                            \n"
"         {                                                                                                         \n"
"             *i = 0;                                                                                               \n"
"         }                                                                                                         \n"
"     }                                                                                                             \n"
" }                                                                                                                 \n"


#else /* defined(OPENCL_DBG_MODE) */


"typedef unsigned char uint8_t;typedef int uint32_t;struct _0_8{const uint32_"
"t _0_5;const uint32_t _0_3;const uint32_t _0_0;const uint32_t _0_1;const uin"
"t32_t _0_7;};void kernel blurH(global uint8_t*_0_a,global const uint8_t*_0_c"
",global const struct _0_8*_0_9){const int y=get_global_id(0);global const ui"
"nt8_t*_0_4=_0_c+y*_0_9->_0_1;global const uint8_t*_0_b=_0_4;const int _0_7=_"
"0_9->_0_7;const int _0_6=_0_7/2;unsigned int _0_d=(*_0_4)*(_0_6+1);for(int k"
"=0;k<_0_6;++k){_0_d+=(*_0_b);_0_b++;}global uint8_t*_0_2=_0_a+y*_0_9->_0_0;c"
"onst int _0_5=_0_9->_0_5;for(int x=0;x<_0_5;++x){_0_d=_0_d+(*_0_b)-(*_0_4);i"
"f(x>_0_6){_0_4++;}if(x<(_0_5-_0_6-1)){_0_b++;}*_0_2=_0_d/_0_7;++_0_2;}if(y<1"
"28){for(global char*i=_0_a,*const e=_0_a+128;i !=e;++i){*i=0;}}}"


#endif /* defined(OPENCL_DBG_MODE) */


;


const unsigned opencl___blur_h_len = sizeof(opencl___blur_h);
