const char opencl___blur_v[] = 


#if defined(OPENCL_DBG_MODE)


" /**                                                                                                                  \n"
"  * @brief   OpenCL kernel used for vertical bluring.                                                                 \n"
"  *                                                                                                                   \n"
"  * @file    blur_h.c                                                                                                 \n"
"  * @author  OSi (Ondrej Sienczak)                                                                                    \n"
"  */                                                                                                                  \n"
"                                                                                                                      \n"
"                                                                                                                      \n"
" typedef unsigned char uint8_t;                                                                                       \n"
" typedef int           uint32_t;                                                                                      \n"
"                                                                                                                      \n"
"                                                                                                                      \n"
" /**                                                                                                                  \n"
"  * @brief   Kernel arguments                                                                                         \n"
"  */                                                                                                                  \n"
" struct Args                                                                                                          \n"
" {                                                                                                                    \n"
"     const uint32_t width;        /**< @brief Frame width */                                                          \n"
"     const uint32_t height;       /**< @brief Frame height */                                                         \n"
"     const uint32_t dst_strive;   /**< @brief Destination line size */                                                \n"
"     const uint32_t src_strive;   /**< @brief Source line size */                                                     \n"
"     const uint32_t size;         /**< @brief Count of items to be calculated */                                      \n"
" };                                                                                                                   \n"
"                                                                                                                      \n"
"                                                                                                                      \n"
" /**                                                                                                                  \n"
"  * @brief   Vertical blur operation                                                                                  \n"
"  *                                                                                                                   \n"
"  * @param   dst     Destination buffer                                                                               \n"
"  * @param   src     Source buffer                                                                                    \n"
"  * @param   args    Arguments of filter                                                                              \n"
"  */                                                                                                                  \n"
" void kernel blurV(global uint8_t*           dst,                                                                     \n"
"                   global const uint8_t*     src,                                                                     \n"
"                   global const struct Args* args)                                                                    \n"
" {                                                                                                                    \n"
"     const int             x           = get_global_id(0);        /* Current thread ID is current row */              \n"
"     global const uint8_t* start       = src + x;                 /* Start and end of kernel */                       \n"
"     global const uint8_t* end         = start;                                                                       \n"
"     const int             size        = args->size;                                                                  \n"
"     const int             size2       = size / 2;                /* Size of one side of the kernel without center */ \n"
"     int                   acc         = (*start) * (size2 + 1);  /* Left half of kernel with first pixel */          \n"
"     const int             src_strive  = args->src_strive;                                                            \n"
"                                                                                                                      \n"
"     /* Right half of kernel */                                                                                       \n"
"     for (int k = 0; k < size2; k++)                                                                                  \n"
"     {                                                                                                                \n"
"         acc += (*end);                                                                                               \n"
"         end += src_strive;                                                                                           \n"
"     }                                                                                                                \n"
"                                                                                                                      \n"
"                                                                                                                      \n"
"     const int       height     = args->height;                                                                       \n"
"     const int       dst_strive = args->dst_strive;                                                                   \n"
"     global uint8_t* current    = dst + x; /* Current destination pixel */                                            \n"
"                                                                                                                      \n"
"     /* Go through the image */                                                                                       \n"
"     for (int y = 0; y < height; y++)                                                                                 \n"
"     {                                                                                                                \n"
"         acc = acc - (*start) + (*end);                                                                               \n"
"                                                                                                                      \n"
"         if (y > size2)                                                                                               \n"
"         {                                                                                                            \n"
"             start += src_strive;                                                                                     \n"
"         }                                                                                                            \n"
"                                                                                                                      \n"
"         if (y < height - size2 - 1)                                                                                  \n"
"         {                                                                                                            \n"
"             end += src_strive;                                                                                       \n"
"         }                                                                                                            \n"
"                                                                                                                      \n"
"         *current = acc / size;                                                                                       \n"
"         current += dst_strive;                                                                                       \n"
"     }                                                                                                                \n"
" }                                                                                                                    \n"


#else /* defined(OPENCL_DBG_MODE) */


"typedef unsigned char uint8_t;typedef int uint32_t;struct _1_8{const uint32_"
"t _1_5;const uint32_t _1_3;const uint32_t _1_0;const uint32_t _1_1;const uin"
"t32_t _1_7;};void kernel blurV(global uint8_t*_1_a,global const uint8_t*_1_c"
",global const struct _1_8*_1_9){const int x=get_global_id(0);global const ui"
"nt8_t*_1_4=_1_c+x;global const uint8_t*_1_b=_1_4;const int _1_7=_1_9->_1_7;c"
"onst int _1_6=_1_7/2;int _1_d=(*_1_4)*(_1_6+1);const int _1_1=_1_9->_1_1;for"
"(int k=0;k<_1_6;k++){_1_d+=(*_1_b);_1_b+=_1_1;}const int _1_3=_1_9->_1_3;con"
"st int _1_0=_1_9->_1_0;global uint8_t*_1_2=_1_a+x;for(int y=0;y<_1_3;y++){_1"
"_d=_1_d-(*_1_4)+(*_1_b);if(y>_1_6){_1_4+=_1_1;}if(y<_1_3-_1_6-1){_1_b+=_1_1;"
"}*_1_2=_1_d/_1_7;_1_2+=_1_0;}}"


#endif /* defined(OPENCL_DBG_MODE) */


;


const unsigned opencl___blur_v_len = sizeof(opencl___blur_v);
