const char opencl___correlate[] = 


#if defined(OPENCL_DBG_MODE)


" /**                                                                                                      \n"
"  * @brief   OpenCL kernel used for calculation of corelation.                                            \n"
"  *                                                                                                       \n"
"  * @file    corelate.c                                                                                   \n"
"  * @author  OSi (Ondrej Sienczak)                                                                        \n"
"  */                                                                                                      \n"
"                                                                                                          \n"
"                                                                                                          \n"
" /**                                                                                                      \n"
"  * @brief   Indexes of arguments                                                                         \n"
"  */                                                                                                      \n"
" enum Corelate_ArgIdx                                                                                     \n"
" {                                                                                                        \n"
"     CORRELATE___WIDTH_CURRENT,  /**< @brief Current frame width */                                       \n"
"     CORRELATE___WIDTH_PREVIOUS, /**< @brief Previous frame width */                                      \n"
"     CORRELATE___FIELD_X,        /**< @brief X coordinate of field */                                     \n"
"     CORRELATE___FIELD_Y,        /**< @brief Y coordinate of field */                                     \n"
"     CORRELATE___FIELD_SIZE,     /**< @brief Size of field */                                             \n"
"     CORRELATE___HEIGHT,         /**< @brief Frame height */                                              \n"
"     CORRELATE___BPP,            /**< @brief Bytes per pixel */                                           \n"
"     CORRELATE___OFFSET_X,       /**< @brief X Offset */                                                  \n"
"     CORRELATE___OFFSET_Y,       /**< @brief Y Offset */                                                  \n"
"     CORRELATE___MAX_SHIFT,      /**< @brief Maximal correlation shift */                                 \n"
"     __CORRELATE___ARGS_CNT      /**< @brief Count of arguments */                                        \n"
" };                                                                                                       \n"
"                                                                                                          \n"
"                                                                                                          \n"
" /**                                                                                                      \n"
"  * @brief   Correlate frames to find best match                                                          \n"
"  *                                                                                                       \n"
"  * @param result    Result of all correlation for every shift                                            \n"
"  * @param current   Current image buffer                                                                 \n"
"  * @param previous  Previous (corelated) image buffer                                                    \n"
"  * @param args      Arguments                                                                            \n"
"  */                                                                                                      \n"
" void kernel correlate(global int*                 result,                                                \n"
"                       global const unsigned char* current,                                               \n"
"                       global const unsigned char* previous,                                              \n"
"                       global const int*           args)                                                  \n"
" {                                                                                                        \n"
"     int widthCurrent   = args[CORRELATE___WIDTH_CURRENT];                                                \n"
"     int widthPrevious  = args[CORRELATE___WIDTH_PREVIOUS];                                               \n"
"     int field_x        = args[CORRELATE___FIELD_X];                                                      \n"
"     int field_y        = args[CORRELATE___FIELD_Y];                                                      \n"
"     int field_size     = args[CORRELATE___FIELD_SIZE];                                                   \n"
"     int height         = args[CORRELATE___HEIGHT];                                                       \n"
"     int bpp            = args[CORRELATE___BPP];                                                          \n"
"     int offsetX        = args[CORRELATE___OFFSET_X];                                                     \n"
"     int offsetY        = args[CORRELATE___OFFSET_Y];                                                     \n"
"     unsigned maxShift  = args[CORRELATE___MAX_SHIFT];                                                    \n"
"                                                                                                          \n"
"     unsigned       idx = get_global_id(0);                                                               \n"
"     offsetX     += idx % maxShift;                                                                       \n"
"     offsetY     += idx / maxShift;                                                                       \n"
"                                                                                                          \n"
"     int s2 = field_size / 2;                                                                             \n"
"     int x  = field_x - s2;                                                                               \n"
"     int y  = field_y - s2;                                                                               \n"
"                                                                                                          \n"
"     unsigned int                sum  = 0;                                                                \n"
"     global const unsigned char* curr = current  + ((x          ) + (y          ) * widthCurrent)  * bpp; \n"
"     global const unsigned char* prev = previous + ((x + offsetX) + (y + offsetY) * widthPrevious) * bpp; \n"
"                                                                                                          \n"
"     for (int j = 0; j < field_size; ++j)                                                                 \n"
"     {                                                                                                    \n"
"         for (int k = 0; k < field_size * bpp; k++)                                                       \n"
"         {                                                                                                \n"
"             sum += abs((int)curr[0] - (int)prev[0]);                                                     \n"
"             curr++;                                                                                      \n"
"             prev++;                                                                                      \n"
"         }                                                                                                \n"
"                                                                                                          \n"
"         curr += (widthCurrent  - field_size) * bpp;                                                      \n"
"         prev += (widthPrevious - field_size) * bpp;                                                      \n"
"     }                                                                                                    \n"
"                                                                                                          \n"
"     result[idx] = sum;                                                                                   \n"
" }                                                                                                        \n"


#else /* defined(OPENCL_DBG_MODE) */


"enum _2_b{_2_1,_2_0,_2_7,_2_8,_2_2,_2_9,_2_a,_2_5,_2_6,_2_3,_2_4};void kerne"
"l correlate(global int*_2_17,global const unsigned char*_2_14,global const u"
"nsigned char*_2_11,global const int*_2_19){int _2_d=_2_19[_2_1];int _2_c=_2_"
"19[_2_0];int _2_12=_2_19[_2_7];int _2_13=_2_19[_2_8];int _2_f=_2_19[_2_2];in"
"t _2_18=_2_19[_2_9];int _2_1d=_2_19[_2_a];int _2_15=_2_19[_2_5];int _2_16=_2"
"_19[_2_6];unsigned _2_10=_2_19[_2_3];unsigned _2_1e=get_global_id(0);_2_15+="
"_2_1e%_2_10;_2_16+=_2_1e/_2_10;int s2=_2_f/2;int x=_2_12-s2;int y=_2_13-s2;u"
"nsigned int _2_1c=0;global const unsigned char*_2_1a=_2_14+((x)+(y)*_2_d)*_2"
"_1d;global const unsigned char*_2_1b=_2_11+((x+_2_15)+(y+_2_16)*_2_c)*_2_1d;"
"for(int j=0;j<_2_f;++j){for(int k=0;k<_2_f*_2_1d;k++){_2_1c+=abs((int)_2_1a["
"0]-(int)_2_1b[0]);_2_1a++;_2_1b++;}_2_1a+=(_2_d-_2_f)*_2_1d;_2_1b+=(_2_c-_2_"
"f)*_2_1d;}_2_17[_2_1e]=_2_1c;}"


#endif /* defined(OPENCL_DBG_MODE) */


;


const unsigned opencl___correlate_len = sizeof(opencl___correlate);
