const char opencl___blur[] = 


#if defined(OPENCL_DBG_MODE)


" /**                                                                                                               \n"
"  * @brief   OpenCL kernel used to calculate equation resolver for                                                 \n"
"  *          reverse barrel distortion correction.                                                                 \n"
"  *                                                                                                                \n"
"  * @file    from_barrel.c                                                                                         \n"
"  * @author  OSi (Ondrej Sienczak)                                                                                 \n"
"  */                                                                                                               \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
" /**                                                                                                               \n"
"  * @brief   Indexes of arguments                                                                                  \n"
"  */                                                                                                               \n"
" enum ArgIdx                                                                                                       \n"
" {                                                                                                                 \n"
"     WIDTH,          /**< @brief Frame width */                                                                    \n"
"     HEIGHT,         /**< @brief Frame height */                                                                   \n"
"     DST_STRIVE,     /**< @brief ? */                                                                              \n"
"     SRC_STRIVE,     /**< @brief ? */                                                                              \n"
"     SIZE,           /**< @brief Count of items to be calculated */                                                \n"
"     __ARGS_CNT      /**< @brief Count of arguments */                                                             \n"
" };                                                                                                                \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
" /**                                                                                                               \n"
"  * @brief   Argument type                                                                                         \n"
"  */                                                                                                               \n"
" union Arg                                                                                                         \n"
" {                                                                                                                 \n"
"     float f;        /**< @brief Argument of float type */                                                         \n"
"     int   i;        /**< @brief Argument of integer type */                                                       \n"
" };                                                                                                                \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
" /**                                                                                                               \n"
"  * @brief   Horizontal blur operation                                                                             \n"
"  *                                                                                                                \n"
"  * @param   dst     Destination buffer                                                                            \n"
"  * @param   src     Source buffer                                                                                 \n"
"  * @param   args    Arguments of filter                                                                           \n"
"  */                                                                                                               \n"
" void kernel blur(global char*            dst,                                                                     \n"
"                  global const char*      src,                                                                     \n"
"                  global const union Arg* args)                                                                    \n"
" {                                                                                                                 \n"
"     const int                   width       = args[WIDTH].i;                                                      \n"
"     const int                   height      = args[HEIGHT].i;                                                     \n"
"     const int                   dst_strive  = args[DST_STRIVE].i;                                                 \n"
"     const int                   src_strive  = args[SRC_STRIVE].i;                                                 \n"
"     const int                   size        = args[SIZE].i;                                                       \n"
"                                                                                                                   \n"
"     const int                   size2       = size / 2; /* Size of one side of the kernel without center */       \n"
"                                                                                                                   \n"
"     const int                   y           = get_global_id(0);        /* Current thread ID is current row */     \n"
"     global const unsigned char* start       = src  + y * src_strive;   /* Start and end of kernel */              \n"
"     global const unsigned char* end         = start;                                                              \n"
"     global unsigned char*       current     = dst  + y * dst_strive;   /* Current destination pixel */            \n"
"     unsigned int                acc         = (*start) * (size2 + 1);  /* Left half of kernel with first pixel */ \n"
"                                                                                                                   \n"
"     /* Right half of kernel */                                                                                    \n"
"     for (int k = 0; k < size2; ++k)                                                                               \n"
"     {                                                                                                             \n"
"         acc += (*end);                                                                                            \n"
"         end++;                                                                                                    \n"
"     }                                                                                                             \n"
"                                                                                                                   \n"
"     /* Go through the image */                                                                                    \n"
"     for (int x = 0; x < width; ++x)                                                                               \n"
"     {                                                                                                             \n"
"         acc = acc + (*end) - (*start);                                                                            \n"
"                                                                                                                   \n"
"         if (x > size2)                                                                                            \n"
"         {                                                                                                         \n"
"             start++;                                                                                              \n"
"         }                                                                                                         \n"
"                                                                                                                   \n"
"         if (x < (width - size2 - 1))                                                                              \n"
"         {                                                                                                         \n"
"             end++;                                                                                                \n"
"         }                                                                                                         \n"
"                                                                                                                   \n"
"         *current = acc / size;                                                                                    \n"
"         ++current;                                                                                                \n"
"     }                                                                                                             \n"
" }                                                                                                                 \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"
"                                                                                                                   \n"


#else /* defined(OPENCL_DBG_MODE) */


"enum ArgIdx{_0,_1,_2,_3,_5,_z};union Arg{float f;int i;};void kernel blur(gl"
"obal char*_d,global const char*_s,global const union Arg*_a){const int _6=_a"
"[_0].i;const int _7=_a[_1].i;const int _8=_a[_2].i;const int _9=_a[_3].i;con"
"st int _A=_a[_5].i;const int _A2=_A/2;const int y=get_global_id(0);global co"
"nst unsigned char*_c=_s+y*_9;global const unsigned char*_e=_c;global unsigne"
"d char*_f=_d+y*_8;unsigned int acc=(*_c)*(_A2+1);for(int k=0;k<_A2;++k){acc+"
"=(*_e);_e++;}for(int x=0;x<_6;++x){acc=acc+(*_e)-(*_c);if(x>_A2){_c++;}if(x<"
"(_6-_A2-1)){_e++;}*_f=acc/_A;++_f;}}"


#endif /* defined(OPENCL_DBG_MODE) */


;


const unsigned opencl___blur_len = sizeof(opencl___blur);
